// src/data/toursSeed.js
// Generated list of 50 tour package objects (for frontend seeding / mocks).
// Each object follows the shape used in your project (title, city, address, period, price, photos, etc.)
// Photos vary across objects (rotated/altered filenames).

const tours = [
    {
        title: "Westminister Bridge",
        city: "London",
        address: {
            line1: "Somewhere in London",
            line2: "",
            city: "London",
            state: "London",
            zip: "00000",
            country: "UK",
        },
        distance: 300,
        price: 99,
        period: { days: 7, nights: 6 },
        maxGroupSize: 10,
        desc: "This is the description for Westminister Bridge tour.",
        reviews: [
            { name: "John Doe", rating: 4.6, comment: "Lovely view and great guide." },
            { name: "Jane Smith", rating: 3.6, comment: "Crowded but worth it." },
        ],
        photos: [
            "/tour-images/tour-img05.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img02.jpg",
            "/tour-images/tour-img08.jpg",
        ],
        featured: true,
    },
    {
        title: "Bali, Indonesia",
        city: "Bali",
        address: {
            line1: "Somewhere in Indonesia",
            line2: "Somewhere in Indonesia",
            city: "Bali",
            state: "Bali",
            zip: "12345",
            country: "Indonesia",
        },
        distance: 400,
        period: { days: 7, nights: 6 },
        price: 129,
        maxGroupSize: 8,
        desc: "Relax on pristine beaches and explore local temples.",
        reviews: [{ name: "Alice Brown", rating: 5.0, comment: "Paradise!" }],
        photos: [
            "/tour-images/tour-img02.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img05.jpg",
            "/tour-images/tour-img08.jpg",
        ],
        featured: true,
    },
    {
        title: "Snowy Mountains, Thailand",
        city: "Bangkok",
        address: {
            line1: "Somewhere in Thailand",
            line2: "",
            city: "Bangkok",
            state: "Bangkok",
            zip: "00000",
            country: "Thailand",
        },
        distance: 500,
        period: { days: 7, nights: 6 },
        price: 109,
        maxGroupSize: 8,
        desc: "Mountain trails and cold breezes—an unusual Thai escape.",
        reviews: [],
        photos: [
            "/tour-images/tour-img08.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img05.jpg",
        ],
        featured: true,
    },
    {
        title: "Beautiful Sunrise, Thailand",
        city: "Phuket",
        address: {
            line1: "Somewhere in Thailand",
            line2: "",
            city: "Phuket",
            state: "Phuket",
            zip: "00000",
            country: "Thailand",
        },
        distance: 500,
        period: { days: 7, nights: 6 },
        price: 119,
        maxGroupSize: 8,
        desc: "Catch serene sunrises from pristine shores.",
        reviews: [{ name: "Traveler X", rating: 4.2, comment: "" }],
        photos: [
            "/tour-images/tour-img05.jpg",
            "/tour-images/tour-img02.jpg",
            "/tour-images/tour-img08.jpg",
        ],
        featured: true,
    },
    {
        title: "Nusa Pendia, Bali",
        city: "Bali",
        address: {
            line1: "Somewhere in Indonesia",
            line2: "",
            city: "Bali",
            state: "Bali",
            zip: "00000",
            country: "Indonesia",
        },
        distance: 480,
        period: { days: 6, nights: 5 },
        price: 139,
        maxGroupSize: 8,
        desc: "Island cliffs, snorkeling and tranquil beaches.",
        reviews: [],
        photos: [
            "/tour-images/tour-img04.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img11.jpg",
        ],
        featured: true,
    },
    {
        title: "Cherry Blossoms Spring",
        city: "Tokyo",
        address: {
            line1: "Somewhere in Japan",
            line2: "",
            city: "Tokyo",
            state: "Tokyo",
            zip: "00000",
            country: "Japan",
        },
        distance: 520,
        period: { days: 5, nights: 4 },
        price: 199,
        maxGroupSize: 12,
        desc: "Witness the legendary sakura in full bloom.",
        reviews: [{ name: "Sato", rating: 4.8, comment: "Amazing blossoms." }],
        photos: [
            "/tour-images/tour-img03.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img05.jpg",
        ],
        featured: true,
    },
    {
        title: "Holmen Lofoten Escape",
        city: "Paris",
        address: {
            line1: "Somewhere in France",
            line2: "",
            city: "Paris",
            state: "Paris",
            zip: "00000",
            country: "France",
        },
        distance: 450,
        period: { days: 8, nights: 7 },
        price: 249,
        maxGroupSize: 10,
        desc: "Coastal fjords and northern lights style nights (region-inspired).",
        reviews: [],
        photos: [
            "/tour-images/tour-img01.jpg",
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img12.jpg",
        ],
        featured: true,
    },
    {
        title: "Snowy Peaks of Bangkok (Mock)",
        city: "Bangkok",
        address: {
            line1: "Somewhere in Thailand",
            line2: "",
            city: "Bangkok",
            state: "Bangkok",
            zip: "00000",
            country: "Thailand",
        },
        distance: 500,
        period: { days: 7, nights: 6 },
        price: 99,
        maxGroupSize: 8,
        desc: "A quirky mountain-style itinerary near Bangkok.",
        reviews: [{ name: "Visitor", rating: 3.9, comment: "" }],
        photos: [
            "/tour-images/tour-img09.jpg",
            "/tour-images/tour-img10.jpg",
            "/tour-images/tour-img02.jpg",
        ],
        featured: true,
    },
    {
        title: "Jaflong River Trip",
        city: "Sylhet",
        address: {
            line1: "Somewhere in Sylhet",
            line2: "",
            city: "Sylhet",
            state: "Sylhet",
            zip: "00000",
            country: "Bangladesh",
        },
        distance: 100,
        period: { days: 3, nights: 2 },
        price: 79,
        maxGroupSize: 5,
        desc: "Waterfront rocks and river adventures.",
        reviews: [],
        photos: [
            "/tour-images/tour-img07.jpg",
            "/tour-images/tour-img05.jpg",
            "/tour-images/tour-img02.jpg",
        ],
        featured: false,
    },
    {
        title: "Cox's Bazar Sea Beach",
        city: "Chittagong",
        address: {
            line1: "Somewhere in Chittagong",
            line2: "",
            city: "Chittagong",
            state: "Chittagong",
            zip: "00000",
            country: "Bangladesh",
        },
        distance: 500,
        period: { days: 4, nights: 3 },
        price: 89,
        maxGroupSize: 8,
        desc: "Longest natural sea beach and relaxed itineraries.",
        reviews: [],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Golden Triangle Delhi",
        city: "Delhi",
        address: {
            line1: "Historic Delhi",
            line2: "",
            city: "Delhi",
            state: "Delhi",
            zip: "110001",
            country: "India",
        },
        distance: 150,
        period: { days: 5, nights: 4 },
        price: 129,
        maxGroupSize: 12,
        desc: "Heritage sites and cultural walks across Delhi-Agra-Jaipur.",
        reviews: [{ name: "Amit", rating: 4.3, comment: "Very informative." }],
        photos: [
            "/tour-images/tour-img01.jpg",
            "/tour-images/tour-img06.jpg",
            "/tour-images/tour-img04.jpg",
        ],
        featured: true,
    },
    {
        title: "Munnar Tea Trails",
        city: "Munnar",
        address: {
            line1: "Kerala Highlands",
            line2: "",
            city: "Munnar",
            state: "Kerala",
            zip: "685612",
            country: "India",
        },
        distance: 220,
        period: { days: 4, nights: 3 },
        price: 139,
        maxGroupSize: 8,
        desc: "Tea garden walks, spice routes and cozy homestays.",
        reviews: [{ name: "Priya", rating: 4.7, comment: "Loved the scenery." }],
        photos: ["/tour-images/tour-img02.jpg", "/tour-images/tour-img06.jpg"],
        featured: false,
    },
    {
        title: "Sapa Countryside Trek",
        city: "Sapa",
        address: {
            line1: "Northern Highlands",
            line2: "",
            city: "Sapa",
            state: "Lao Cai",
            zip: "330000",
            country: "Vietnam",
        },
        distance: 340,
        period: { days: 6, nights: 5 },
        price: 169,
        maxGroupSize: 10,
        desc: "Rice terraces, local markets and scenic treks.",
        reviews: [],
        photos: ["/tour-images/tour-img03.jpg", "/tour-images/tour-img09.jpg"],
        featured: true,
    },
    {
        title: "Istanbul Heritage Walk",
        city: "Istanbul",
        address: {
            line1: "Old City",
            line2: "",
            city: "Istanbul",
            state: "Istanbul",
            zip: "34000",
            country: "Turkey",
        },
        distance: 320,
        period: { days: 5, nights: 4 },
        price: 149,
        maxGroupSize: 14,
        desc: "Mosques, bazaars and Bosphorus views.",
        reviews: [{ name: "Erdem", rating: 4.4, comment: "Great local guide." }],
        photos: [
            "/tour-images/tour-img04.jpg",
            "/tour-images/tour-img08.jpg",
            "/tour-images/tour-img10.jpg",
        ],
        featured: true,
    },
    {
        title: "Santorini Sunset Cruise",
        city: "Santorini",
        address: {
            line1: "Caldera Edge",
            line2: "",
            city: "Santorini",
            state: "Thira",
            zip: "84700",
            country: "Greece",
        },
        distance: 410,
        period: { days: 3, nights: 2 },
        price: 199,
        maxGroupSize: 20,
        desc: "Romantic sunsets and sea cruises around caldera cliffs.",
        reviews: [{ name: "Nikos", rating: 4.9, comment: "Magical evening." }],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img01.jpg"],
        featured: true,
    },
    {
        title: "Machu Picchu Classic",
        city: "Cusco",
        address: {
            line1: "Sacred Valley",
            line2: "",
            city: "Cusco",
            state: "Cusco",
            zip: "08000",
            country: "Peru",
        },
        distance: 1200,
        period: { days: 5, nights: 4 },
        price: 399,
        maxGroupSize: 12,
        desc: "Ancient ruins, highland treks and rich Inca history.",
        reviews: [{ name: "Carlos", rating: 4.8, comment: "Breathtaking." }],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img05.jpg"],
        featured: true,
    },
    {
        title: "Patagonia Adventure",
        city: "El Calafate",
        address: {
            line1: "Glacier Route",
            line2: "",
            city: "El Calafate",
            state: "Santa Cruz",
            zip: "9405",
            country: "Argentina",
        },
        distance: 1800,
        period: { days: 9, nights: 8 },
        price: 799,
        maxGroupSize: 8,
        desc: "Glaciers, hiking and remote wilderness.",
        reviews: [],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Great Barrier Reef Dive",
        city: "Cairns",
        address: {
            line1: "Coral Coast",
            line2: "",
            city: "Cairns",
            state: "Queensland",
            zip: "4870",
            country: "Australia",
        },
        distance: 950,
        period: { days: 6, nights: 5 },
        price: 499,
        maxGroupSize: 10,
        desc: "Snorkeling, diving and marine life exploration.",
        reviews: [{ name: "Liam", rating: 4.6, comment: "Unreal coral colors." }],
        photos: ["/tour-images/tour-img07.jpg", "/tour-images/tour-img02.jpg"],
        featured: true,
    },
    {
        title: "Seychelles Island Hopper",
        city: "Mahé",
        address: {
            line1: "Tropical Shores",
            line2: "",
            city: "Mahé",
            state: "Mahé",
            zip: "0000",
            country: "Seychelles",
        },
        distance: 1200,
        period: { days: 7, nights: 6 },
        price: 699,
        maxGroupSize: 12,
        desc: "Secluded beaches, snorkeling and island vibes.",
        reviews: [],
        photos: ["/tour-images/tour-img08.jpg", "/tour-images/tour-img03.jpg"],
        featured: true,
    },
    {
        title: "Morocco Desert Camp",
        city: "Marrakech",
        address: {
            line1: "Sahara Outskirts",
            line2: "",
            city: "Marrakech",
            state: "Marrakech",
            zip: "40000",
            country: "Morocco",
        },
        distance: 600,
        period: { days: 4, nights: 3 },
        price: 219,
        maxGroupSize: 10,
        desc: "Camel rides, dunes and overnight desert camps.",
        reviews: [{ name: "Youssef", rating: 4.1, comment: "Unique experience." }],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img04.jpg"],
        featured: false,
    },
    {
        title: "Iceland Ring Road",
        city: "Reykjavik",
        address: {
            line1: "Scenic Route",
            line2: "",
            city: "Reykjavik",
            state: "Capital Region",
            zip: "101",
            country: "Iceland",
        },
        distance: 2000,
        period: { days: 10, nights: 9 },
        price: 999,
        maxGroupSize: 12,
        desc: "Waterfalls, glaciers and volcanic landscapes.",
        reviews: [{ name: "Bjorn", rating: 4.9, comment: "Epic scenery." }],
        photos: ["/tour-images/tour-img10.jpg", "/tour-images/tour-img06.jpg"],
        featured: true,
    },
    {
        title: "Alaska Wildlife Cruise",
        city: "Juneau",
        address: {
            line1: "Glacier Bay",
            line2: "",
            city: "Juneau",
            state: "Alaska",
            zip: "99801",
            country: "USA",
        },
        distance: 1600,
        period: { days: 7, nights: 6 },
        price: 799,
        maxGroupSize: 30,
        desc: "Whales, glaciers and coastal wildlife viewing.",
        reviews: [{ name: "Megan", rating: 4.5, comment: "Saw whales up close." }],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img02.jpg"],
        featured: true,
    },
    {
        title: "Canadian Rockies Round",
        city: "Banff",
        address: {
            line1: "Rocky Path",
            line2: "",
            city: "Banff",
            state: "Alberta",
            zip: "T1L",
            country: "Canada",
        },
        distance: 900,
        period: { days: 6, nights: 5 },
        price: 449,
        maxGroupSize: 10,
        desc: "Lakes, peaks and alpine trails.",
        reviews: [{ name: "Oliver", rating: 4.7, comment: "Stunning turquoise lakes." }],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img05.jpg"],
        featured: false,
    },
    {
        title: "Berlin City Culture",
        city: "Berlin",
        address: {
            line1: "Central Berlin",
            line2: "",
            city: "Berlin",
            state: "Berlin",
            zip: "10115",
            country: "Germany",
        },
        distance: 250,
        period: { days: 3, nights: 2 },
        price: 129,
        maxGroupSize: 15,
        desc: "Street art, museums and vibrant nightlife.",
        reviews: [{ name: "Hanna", rating: 4.2, comment: "Great food scene." }],
        photos: ["/tour-images/tour-img01.jpg", "/tour-images/tour-img08.jpg"],
        featured: false,
    },
    {
        title: "Lisbon Coastal Escape",
        city: "Lisbon",
        address: {
            line1: "Old Harbor",
            line2: "",
            city: "Lisbon",
            state: "Lisboa",
            zip: "1100",
            country: "Portugal",
        },
        distance: 360,
        period: { days: 4, nights: 3 },
        price: 179,
        maxGroupSize: 12,
        desc: "Cliffs, historic trams and seafood bays.",
        reviews: [],
        photos: ["/tour-images/tour-img03.jpg", "/tour-images/tour-img07.jpg"],
        featured: true,
    },
    {
        title: "Prague Fairy Tale",
        city: "Prague",
        address: {
            line1: "Charles Bridge Area",
            line2: "",
            city: "Prague",
            state: "Prague",
            zip: "11000",
            country: "Czech Republic",
        },
        distance: 280,
        period: { days: 3, nights: 2 },
        price: 139,
        maxGroupSize: 14,
        desc: "Cobblestone lanes, castles and riverside charm.",
        reviews: [{ name: "Katerina", rating: 4.5, comment: "Beautiful old town." }],
        photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Budapest Spa & Danube",
        city: "Budapest",
        address: {
            line1: "Thermal Baths District",
            line2: "",
            city: "Budapest",
            state: "Budapest",
            zip: "1051",
            country: "Hungary",
        },
        distance: 310,
        period: { days: 4, nights: 3 },
        price: 149,
        maxGroupSize: 12,
        desc: "Historic baths, river cruises and classical architecture.",
        reviews: [],
        photos: ["/tour-images/tour-img05.jpg", "/tour-images/tour-img10.jpg"],
        featured: false,
    },
    {
        title: "Buenos Aires Tango Nights",
        city: "Buenos Aires",
        address: {
            line1: "San Telmo Streets",
            line2: "",
            city: "Buenos Aires",
            state: "Buenos Aires",
            zip: "C1066",
            country: "Argentina",
        },
        distance: 1300,
        period: { days: 5, nights: 4 },
        price: 299,
        maxGroupSize: 10,
        desc: "Dance, cuisine and historic barrios.",
        reviews: [{ name: "Sofia", rating: 4.6, comment: "Loved the local tango show." }],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img11.jpg"],
        featured: true,
    },
    {
        title: "Zanzibar Spice Tour",
        city: "Zanzibar",
        address: {
            line1: "Stone Town",
            line2: "",
            city: "Zanzibar",
            state: "Zanzibar",
            zip: "7200",
            country: "Tanzania",
        },
        distance: 1100,
        period: { days: 6, nights: 5 },
        price: 399,
        maxGroupSize: 8,
        desc: "Spice markets, historic alleys and coastal relaxation.",
        reviews: [],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Seoul Modern + Tradition",
        city: "Seoul",
        address: {
            line1: "Gwanghwamun",
            line2: "",
            city: "Seoul",
            state: "Seoul",
            zip: "03172",
            country: "South Korea",
        },
        distance: 420,
        period: { days: 4, nights: 3 },
        price: 219,
        maxGroupSize: 16,
        desc: "Palaces, street markets and K-culture tours.",
        reviews: [{ name: "Min", rating: 4.4, comment: "Great mix of old and new." }],
        photos: ["/tour-images/tour-img01.jpg", "/tour-images/tour-img03.jpg"],
        featured: true,
    },
    {
        title: "Yangon Colonial Walk",
        city: "Yangon",
        address: {
            line1: "Colonial Quarter",
            line2: "",
            city: "Yangon",
            state: "Yangon",
            zip: "11001",
            country: "Myanmar",
        },
        distance: 260,
        period: { days: 3, nights: 2 },
        price: 99,
        maxGroupSize: 12,
        desc: "Shops, pagodas and bustling markets.",
        reviews: [],
        photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img08.jpg"],
        featured: false,
    },
    {
        title: "Laos Mekong Slow Boat",
        city: "Luang Prabang",
        address: {
            line1: "Riverside",
            line2: "",
            city: "Luang Prabang",
            state: "Luang Prabang",
            zip: "06000",
            country: "Laos",
        },
        distance: 380,
        period: { days: 5, nights: 4 },
        price: 159,
        maxGroupSize: 10,
        desc: "Gentle river cruising and village visits.",
        reviews: [],
        photos: ["/tour-images/tour-img05.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Hanoi Street Food Crawl",
        city: "Hanoi",
        address: {
            line1: "Old Quarter",
            line2: "",
            city: "Hanoi",
            state: "Hanoi",
            zip: "10000",
            country: "Vietnam",
        },
        distance: 200,
        period: { days: 2, nights: 1 },
        price: 59,
        maxGroupSize: 20,
        desc: "Taste local bites with expert guides.",
        reviews: [{ name: "Linh", rating: 4.6, comment: "Fantastic flavors." }],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img10.jpg"],
        featured: true,
    },
    {
        title: "Amalfi Coast Drive",
        city: "Amalfi",
        address: {
            line1: "Coastal Road",
            line2: "",
            city: "Amalfi",
            state: "Campania",
            zip: "84011",
            country: "Italy",
        },
        distance: 380,
        period: { days: 4, nights: 3 },
        price: 279,
        maxGroupSize: 8,
        desc: "Coastal vistas, lemon groves and cliffside towns.",
        reviews: [],
        photos: ["/tour-images/tour-img07.jpg", "/tour-images/tour-img01.jpg"],
        featured: true,
    },
    {
        title: "Tanzania Safari Basic",
        city: "Arusha",
        address: {
            line1: "Savannah Trails",
            line2: "",
            city: "Arusha",
            state: "Arusha",
            zip: "00000",
            country: "Tanzania",
        },
        distance: 900,
        period: { days: 6, nights: 5 },
        price: 549,
        maxGroupSize: 10,
        desc: "Big five sightings and camp nights under stars.",
        reviews: [{ name: "Moses", rating: 4.7, comment: "Incredible wildlife." }],
        photos: ["/tour-images/tour-img08.jpg", "/tour-images/tour-img11.jpg"],
        featured: true,
    },
    {
        title: "Kerala Backwaters Cruise",
        city: "Alleppey",
        address: {
            line1: "Houseboat Landing",
            line2: "",
            city: "Alleppey",
            state: "Kerala",
            zip: "688011",
            country: "India",
        },
        distance: 180,
        period: { days: 2, nights: 1 },
        price: 129,
        maxGroupSize: 6,
        desc: "Houseboat stays, village life and calm waterways.",
        reviews: [{ name: "Anil", rating: 4.5, comment: "Relaxing and scenic." }],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img03.jpg"],
        featured: false,
    },
    {
        title: "Yangtze River Highlights",
        city: "Chongqing",
        address: {
            line1: "River Dock",
            line2: "",
            city: "Chongqing",
            state: "Sichuan",
            zip: "400000",
            country: "China",
        },
        distance: 1400,
        period: { days: 7, nights: 6 },
        price: 449,
        maxGroupSize: 20,
        desc: "Scenic gorges and cultural sites along the river.",
        reviews: [],
        photos: ["/tour-images/tour-img10.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Rajasthan Palace Trail",
        city: "Jaipur",
        address: {
            line1: "Royal Circuit",
            line2: "",
            city: "Jaipur",
            state: "Rajasthan",
            zip: "302001",
            country: "India",
        },
        distance: 320,
        period: { days: 6, nights: 5 },
        price: 229,
        maxGroupSize: 12,
        desc: "Palaces, forts and desert heritage camps.",
        reviews: [{ name: "Ravi", rating: 4.6, comment: "Well organized." }],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img05.jpg"],
        featured: true,
    },
    {
        title: "Kyoto Temple Retreat",
        city: "Kyoto",
        address: {
            line1: "Historic Kyoto",
            line2: "",
            city: "Kyoto",
            state: "Kyoto",
            zip: "600-0000",
            country: "Japan",
        },
        distance: 410,
        period: { days: 4, nights: 3 },
        price: 239,
        maxGroupSize: 10,
        desc: "Zen gardens, temples and cultural experiences.",
        reviews: [{ name: "Hiro", rating: 4.8, comment: "Peaceful stay." }],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img06.jpg"],
        featured: true,
    },
    {
        title: "Oman Coastal Expedition",
        city: "Muscat",
        address: {
            line1: "Corniche Route",
            line2: "",
            city: "Muscat",
            state: "Muscat",
            zip: "113",
            country: "Oman",
        },
        distance: 700,
        period: { days: 5, nights: 4 },
        price: 349,
        maxGroupSize: 12,
        desc: "Coastal forts, wadis and sea adventures.",
        reviews: [],
        photos: ["/tour-images/tour-img01.jpg", "/tour-images/tour-img07.jpg"],
        featured: false,
    },
    {
        title: "Philippines Island Jump",
        city: "Palawan",
        address: {
            line1: "El Nido Bays",
            line2: "",
            city: "El Nido",
            state: "Palawan",
            zip: "5313",
            country: "Philippines",
        },
        distance: 850,
        period: { days: 6, nights: 5 },
        price: 399,
        maxGroupSize: 10,
        desc: "Hidden lagoons and island-hopping adventures.",
        reviews: [{ name: "Marco", rating: 4.7, comment: "Crystal clear waters." }],
        photos: ["/tour-images/tour-img02.jpg", "/tour-images/tour-img08.jpg"],
        featured: true,
    },
    {
        title: "Singapore City Lights",
        city: "Singapore",
        address: {
            line1: "Marina Bay",
            line2: "",
            city: "Singapore",
            state: "Central",
            zip: "018956",
            country: "Singapore",
        },
        distance: 220,
        period: { days: 3, nights: 2 },
        price: 189,
        maxGroupSize: 18,
        desc: "Futuristic skyline, gardens and food havens.",
        reviews: [{ name: "Wei", rating: 4.4, comment: "Great city energy." }],
        photos: ["/tour-images/tour-img03.jpg", "/tour-images/tour-img11.jpg"],
        featured: false,
    },
    {
        title: "Raja Ampat Diving",
        city: "Raja Ampat",
        address: {
            line1: "Coral Rich Zone",
            line2: "",
            city: "Raja Ampat",
            state: "Papua",
            zip: "98000",
            country: "Indonesia",
        },
        distance: 1300,
        period: { days: 8, nights: 7 },
        price: 899,
        maxGroupSize: 8,
        desc: "World-class diving and remote island exploration.",
        reviews: [],
        photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img12.jpg"],
        featured: true,
    },
    {
        title: "St. Petersburg Palaces",
        city: "St. Petersburg",
        address: {
            line1: "Neva Embankment",
            line2: "",
            city: "St. Petersburg",
            state: "St. Petersburg",
            zip: "190000",
            country: "Russia",
        },
        distance: 820,
        period: { days: 5, nights: 4 },
        price: 299,
        maxGroupSize: 12,
        desc: "Imperial palaces, canals and rich arts.",
        reviews: [{ name: "Irina", rating: 4.3, comment: "Beautiful museums." }],
        photos: ["/tour-images/tour-img05.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Camino de Santiago Walk",
        city: "Santiago",
        address: {
            line1: "Pilgrim Route",
            line2: "",
            city: "Santiago de Compostela",
            state: "Galicia",
            zip: "15705",
            country: "Spain",
        },
        distance: 1100,
        period: { days: 12, nights: 11 },
        price: 599,
        maxGroupSize: 10,
        desc: "Historic pilgrimage route through Spanish countryside.",
        reviews: [{ name: "Pablo", rating: 4.9, comment: "A life-changing trek." }],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img10.jpg"],
        featured: true,
    },
    {
        title: "Namibia Desert & Dunes",
        city: "Windhoek",
        address: {
            line1: "Desert Edge",
            line2: "",
            city: "Windhoek",
            state: "Khomas",
            zip: "9000",
            country: "Namibia",
        },
        distance: 1500,
        period: { days: 7, nights: 6 },
        price: 749,
        maxGroupSize: 8,
        desc: "Red dunes, moonscape pans and wildlife.",
        reviews: [],
        photos: ["/tour-images/tour-img07.jpg", "/tour-images/tour-img01.jpg"],
        featured: false,
    },
    {
        title: "Balkan Roadtrip",
        city: "Zagreb",
        address: {
            line1: "Scenic Balkans",
            line2: "",
            city: "Zagreb",
            state: "Zagreb",
            zip: "10000",
            country: "Croatia",
        },
        distance: 900,
        period: { days: 9, nights: 8 },
        price: 459,
        maxGroupSize: 12,
        desc: "Historic towns, coastlines and mountain passes.",
        reviews: [],
        photos: ["/tour-images/tour-img08.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Hokkaido Snow Festival",
        city: "Sapporo",
        address: {
            line1: "Festival Grounds",
            line2: "",
            city: "Sapporo",
            state: "Hokkaido",
            zip: "060-0000",
            country: "Japan",
        },
        distance: 600,
        period: { days: 4, nights: 3 },
        price: 279,
        maxGroupSize: 12,
        desc: "Snow sculptures, winter foods and local culture.",
        reviews: [{ name: "Yuki", rating: 4.7, comment: "Charming festival." }],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img11.jpg"],
        featured: true,
    },
    {
        title: "Marrakesh Medina Markets",
        city: "Marrakech",
        address: {
            line1: "Souk District",
            line2: "",
            city: "Marrakech",
            state: "Marrakech",
            zip: "40000",
            country: "Morocco",
        },
        distance: 350,
        period: { days: 3, nights: 2 },
        price: 129,
        maxGroupSize: 10,
        desc: "Colors, textiles and spice aromas of the medina.",
        reviews: [],
        photos: ["/tour-images/tour-img10.jpg", "/tour-images/tour-img03.jpg"],
        featured: false,
    },
    {
        title: "Azores Whale Watching",
        city: "Ponta Delgada",
        address: {
            line1: "Atlantic Shores",
            line2: "",
            city: "Ponta Delgada",
            state: "Azores",
            zip: "9500",
            country: "Portugal",
        },
        distance: 1400,
        period: { days: 5, nights: 4 },
        price: 329,
        maxGroupSize: 12,
        desc: "Deep-sea spotting and island nature.",
        reviews: [],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img04.jpg"],
        featured: true,
    },
    {
        title: "Tbilisi Wine & Walks",
        city: "Tbilisi",
        address: {
            line1: "Old Town",
            line2: "",
            city: "Tbilisi",
            state: "Tbilisi",
            zip: "0105",
            country: "Georgia",
        },
        distance: 320,
        period: { days: 3, nights: 2 },
        price: 119,
        maxGroupSize: 14,
        desc: "Cafes, wine cellars and hillside views.",
        reviews: [{ name: "Nino", rating: 4.2, comment: "Great vineyards nearby." }],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img06.jpg"],
        featured: false,
    },
    {
        title: "Belize Barrier Reef Snorkel",
        city: "San Pedro",
        address: {
            line1: "Ambergris Caye",
            line2: "",
            city: "San Pedro",
            state: "Belize District",
            zip: "00000",
            country: "Belize",
        },
        distance: 900,
        period: { days: 4, nights: 3 },
        price: 279,
        maxGroupSize: 12,
        desc: "Coral gardens, marine life and relaxed island vibes.",
        reviews: [],
        photos: ["/tour-images/tour-img01.jpg", "/tour-images/tour-img07.jpg"],
        featured: true,
    },
    {
        title: "Fjord & Sauna Norway",
        city: "Bergen",
        address: {
            line1: "Fjord Access",
            line2: "",
            city: "Bergen",
            state: "Vestland",
            zip: "5003",
            country: "Norway",
        },
        distance: 600,
        period: { days: 5, nights: 4 },
        price: 399,
        maxGroupSize: 10,
        desc: "Scenic fjords and Nordic wellness.",
        reviews: [{ name: "Erik", rating: 4.6, comment: "Refreshing trip." }],
        photos: ["/tour-images/tour-img02.jpg", "/tour-images/tour-img08.jpg"],
        featured: true,
    },
    {
        title: "Madagascar Baobab Route",
        city: "Morondava",
        address: {
            line1: "Baobab Alley",
            line2: "",
            city: "Morondava",
            state: "Menabe",
            zip: "000",
            country: "Madagascar",
        },
        distance: 1600,
        period: { days: 8, nights: 7 },
        price: 689,
        maxGroupSize: 8,
        desc: "Unique trees, biodiversity and remote beaches.",
        reviews: [],
        photos: ["/tour-images/tour-img03.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Greece Island Hopping",
        city: "Mykonos",
        address: {
            line1: "Aegean Isles",
            line2: "",
            city: "Mykonos",
            state: "South Aegean",
            zip: "84600",
            country: "Greece",
        },
        distance: 430,
        period: { days: 6, nights: 5 },
        price: 349,
        maxGroupSize: 14,
        desc: "Beach clubs, windmills and blue-capped roofs.",
        reviews: [{ name: "Elena", rating: 4.7, comment: "Great beaches." }],
        photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img10.jpg"],
        featured: true,
    },
    {
        title: "Nepal Annapurna Base",
        city: "Pokhara",
        address: {
            line1: "Himalayan Outskirts",
            line2: "",
            city: "Pokhara",
            state: "Gandaki",
            zip: "33700",
            country: "Nepal",
        },
        distance: 700,
        period: { days: 10, nights: 9 },
        price: 499,
        maxGroupSize: 12,
        desc: "Trekking, villages and Himalayan panorama.",
        reviews: [{ name: "Sita", rating: 4.9, comment: "Tough but rewarding." }],
        photos: ["/tour-images/tour-img05.jpg", "/tour-images/tour-img11.jpg"],
        featured: true,
    },
    {
        title: "Amazon Rainforest Lodge",
        city: "Iquitos",
        address: {
            line1: "Amazon Basin",
            line2: "",
            city: "Iquitos",
            state: "Loreto",
            zip: "16000",
            country: "Peru",
        },
        distance: 1300,
        period: { days: 7, nights: 6 },
        price: 559,
        maxGroupSize: 8,
        desc: "Jungle nights, wildlife and river life.",
        reviews: [],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img12.jpg"],
        featured: false,
    },
    {
        title: "Cuba Classic Havana",
        city: "Havana",
        address: {
            line1: "Old Havana",
            line2: "",
            city: "Havana",
            state: "Havana",
            zip: "10100",
            country: "Cuba",
        },
        distance: 780,
        period: { days: 5, nights: 4 },
        price: 249,
        maxGroupSize: 12,
        desc: "Classic cars, music and authentic culture.",
        reviews: [{ name: "Diego", rating: 4.3, comment: "Vibrant streets." }],
        photos: ["/tour-images/tour-img07.jpg", "/tour-images/tour-img01.jpg"],
        featured: false,
    },
    {
        title: "Bournemouth Coastal Break",
        city: "Bournemouth",
        address: {
            line1: "South Coast",
            line2: "",
            city: "Bournemouth",
            state: "Dorset",
            zip: "BH1",
            country: "UK",
        },
        distance: 210,
        period: { days: 2, nights: 1 },
        price: 69,
        maxGroupSize: 20,
        desc: "Short seaside getaway with coastal walks.",
        reviews: [],
        photos: ["/tour-images/tour-img08.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Casablanca Cultural Tour",
        city: "Casablanca",
        address: {
            line1: "City Center",
            line2: "",
            city: "Casablanca",
            state: "Casablanca-Settat",
            zip: "20000",
            country: "Morocco",
        },
        distance: 360,
        period: { days: 4, nights: 3 },
        price: 159,
        maxGroupSize: 14,
        desc: "Architecture, food and local markets.",
        reviews: [],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img03.jpg"],
        featured: false,
    },
    {
        title: "Dublin Pub & History",
        city: "Dublin",
        address: {
            line1: "Temple Bar",
            line2: "",
            city: "Dublin",
            state: "Leinster",
            zip: "D02",
            country: "Ireland",
        },
        distance: 240,
        period: { days: 3, nights: 2 },
        price: 129,
        maxGroupSize: 18,
        desc: "Pubs, storytelling and historical sites.",
        reviews: [{ name: "Sean", rating: 4.2, comment: "Lively nights." }],
        photos: ["/tour-images/tour-img10.jpg", "/tour-images/tour-img04.jpg"],
        featured: false,
    },
    {
        title: "Santiago Andes Explorer",
        city: "Santiago",
        address: {
            line1: "Mountain Gateway",
            line2: "",
            city: "Santiago",
            state: "Santiago Metropolitan",
            zip: "8320000",
            country: "Chile",
        },
        distance: 1000,
        period: { days: 6, nights: 5 },
        price: 399,
        maxGroupSize: 12,
        desc: "Andean foothills, vineyards and scenic drives.",
        reviews: [],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img05.jpg"],
        featured: false,
    },
    {
        title: "Kigali Cultural Circuit",
        city: "Kigali",
        address: {
            line1: "City Hub",
            line2: "",
            city: "Kigali",
            state: "Kigali",
            zip: "00000",
            country: "Rwanda",
        },
        distance: 310,
        period: { days: 3, nights: 2 },
        price: 149,
        maxGroupSize: 12,
        desc: "Museums, markets and local cuisine.",
        reviews: [],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img06.jpg"],
        featured: false,
    },
    {
        title: "Zagreb Autumn Hike",
        city: "Zagreb",
        address: {
            line1: "Hill Trails",
            line2: "",
            city: "Zagreb",
            state: "Zagreb",
            zip: "10000",
            country: "Croatia",
        },
        distance: 200,
        period: { days: 2, nights: 1 },
        price: 89,
        maxGroupSize: 10,
        desc: "Short hikes and scenic viewpoints in autumn hues.",
        reviews: [{ name: "Ivan", rating: 4.1, comment: "Refreshing weekend." }],
        photos: ["/tour-images/tour-img01.jpg", "/tour-images/tour-img07.jpg"],
        featured: false,
    },
    {
        title: "Lima Gastronomy Tour",
        city: "Lima",
        address: {
            line1: "Gourmet Quarter",
            line2: "",
            city: "Lima",
            state: "Lima",
            zip: "15000",
            country: "Peru",
        },
        distance: 780,
        period: { days: 4, nights: 3 },
        price: 219,
        maxGroupSize: 12,
        desc: "Peruvian flavors, ceviche workshops and market visits.",
        reviews: [{ name: "Diego", rating: 4.8, comment: "Tasty journey." }],
        photos: ["/tour-images/tour-img02.jpg", "/tour-images/tour-img08.jpg"],
        featured: true,
    },
    {
        title: "Accra Coastal Markets",
        city: "Accra",
        address: {
            line1: "Market District",
            line2: "",
            city: "Accra",
            state: "Greater Accra",
            zip: "00000",
            country: "Ghana",
        },
        distance: 420,
        period: { days: 3, nights: 2 },
        price: 99,
        maxGroupSize: 16,
        desc: "Markets, beaches and coastal food stalls.",
        reviews: [],
        photos: ["/tour-images/tour-img03.jpg", "/tour-images/tour-img09.jpg"],
        featured: false,
    },
    {
        title: "Fes Artisan Trails",
        city: "Fes",
        address: {
            line1: "Medina Lab",
            line2: "",
            city: "Fes",
            state: "Fes-Meknes",
            zip: "30000",
            country: "Morocco",
        },
        distance: 320,
        period: { days: 3, nights: 2 },
        price: 119,
        maxGroupSize: 10,
        desc: "Handicrafts, alleyways and traditional workshops.",
        reviews: [],
        photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img10.jpg"],
        featured: false,
    },
    {
        title: "Manila Heritage & Bays",
        city: "Manila",
        address: {
            line1: "Intramuros District",
            line2: "",
            city: "Manila",
            state: "Metro Manila",
            zip: "1000",
            country: "Philippines",
        },
        distance: 200,
        period: { days: 2, nights: 1 },
        price: 79,
        maxGroupSize: 20,
        desc: "Historic fortresses and bay strolls.",
        reviews: [],
        photos: ["/tour-images/tour-img05.jpg", "/tour-images/tour-img11.jpg"],
        featured: false,
    },
    {
        title: "Riga Old Town Stroll",
        city: "Riga",
        address: {
            line1: "Medieval Quarter",
            line2: "",
            city: "Riga",
            state: "Riga",
            zip: "1050",
            country: "Latvia",
        },
        distance: 240,
        period: { days: 2, nights: 1 },
        price: 99,
        maxGroupSize: 14,
        desc: "Art nouveau facades and riverside cafes.",
        reviews: [{ name: "Anna", rating: 4.0, comment: "Charming town." }],
        photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img12.jpg"],
        featured: false,
    },
    {
        title: "Tallinn Winter Markets",
        city: "Tallinn",
        address: {
            line1: "Old City",
            line2: "",
            city: "Tallinn",
            state: "Harju",
            zip: "10111",
            country: "Estonia",
        },
        distance: 260,
        period: { days: 3, nights: 2 },
        price: 119,
        maxGroupSize: 12,
        desc: "Medieval squares and seasonal markets.",
        reviews: [],
        photos: ["/tour-images/tour-img07.jpg", "/tour-images/tour-img01.jpg"],
        featured: false,
    },
    {
        title: "Valparaiso Colorful Hills",
        city: "Valparaiso",
        address: {
            line1: "Seaside Cliffs",
            line2: "",
            city: "Valparaiso",
            state: "Valparaiso",
            zip: "2340000",
            country: "Chile",
        },
        distance: 1200,
        period: { days: 4, nights: 3 },
        price: 199,
        maxGroupSize: 10,
        desc: "Street art, funiculars and coastal views.",
        reviews: [],
        photos: ["/tour-images/tour-img08.jpg", "/tour-images/tour-img02.jpg"],
        featured: false,
    },
    {
        title: "Kuala Lumpur City Highlights",
        city: "Kuala Lumpur",
        address: {
            line1: "KLCC District",
            line2: "",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            zip: "50088",
            country: "Malaysia",
        },
        distance: 210,
        period: { days: 3, nights: 2 },
        price: 129,
        maxGroupSize: 20,
        desc: "Skyscrapers, markets and cultural islands.",
        reviews: [{ name: "Ahmad", rating: 4.1, comment: "Great diversity." }],
        photos: ["/tour-images/tour-img09.jpg", "/tour-images/tour-img03.jpg"],
        featured: false,
    },
    {
        title: "Rotorua Geothermal Trails",
        city: "Rotorua",
        address: {
            line1: "Thermal Parks",
            line2: "",
            city: "Rotorua",
            state: "Bay of Plenty",
            zip: "3010",
            country: "New Zealand",
        },
        distance: 520,
        period: { days: 4, nights: 3 },
        price: 259,
        maxGroupSize: 10,
        desc: "Geysers, Maori culture and hot springs.",
        reviews: [{ name: "Hana", rating: 4.5, comment: "Cultural depth." }],
        photos: ["/tour-images/tour-img10.jpg", "/tour-images/tour-img04.jpg"],
        featured: true,
    },
    {
        title: "Kampala City & Lake Views",
        city: "Kampala",
        address: {
            line1: "Lakeside",
            line2: "",
            city: "Kampala",
            state: "Central",
            zip: "00000",
            country: "Uganda",
        },
        distance: 320,
        period: { days: 3, nights: 2 },
        price: 119,
        maxGroupSize: 16,
        desc: "City rhythms and nearby lake escapes.",
        reviews: [],
        photos: ["/tour-images/tour-img11.jpg", "/tour-images/tour-img05.jpg"],
        featured: false,
    },
    {
        title: "Hobart Wilderness & Food",
        city: "Hobart",
        address: {
            line1: "Derwent River",
            line2: "",
            city: "Hobart",
            state: "Tasmania",
            zip: "7000",
            country: "Australia",
        },
        distance: 680,
        period: { days: 5, nights: 4 },
        price: 299,
        maxGroupSize: 12,
        desc: "Local produce markets and rugged wilderness.",
        reviews: [],
        photos: ["/tour-images/tour-img12.jpg", "/tour-images/tour-img06.jpg"],
        featured: false,
    },
];

export default tours;
