const tours = [
  {
    title: "Westminister Bridge",
    city: "London",
    address: {
      line1: "Somewhere in London",
      line2: "",
      city: "London",
      state: "London",
      zip: "00000",
      country: "UK",
    },
    distance: 300,
    price: 99,
    period: {
      days: 7,
      nights: 6,
    },
    maxGroupSize: 10,
    desc: "this is the description",
    reviews: [
      {name: "John Doe", rating: 4.6, comment: "Lovely view and great guide."},
      {name: "Jane Smith", rating: 3.6, comment: "Crowded but worth it."},
    ],
    photos: [
      "/tour-images/tour-img01.jpg",
      "/tour-images/tour-img01-2.jpg",
      "/tour-images/tour-img01-3.jpg",
    ],
    featured: true,
  },
  {
    title: "Bali, Indonesia",
    city: "Bali",
    address: {
      line1: "Somewhere in Indonesia",
      line2: "Somewhere in Indonesia",
      city: "Bali",
      state: "Bali",
      zip: "12345",
      country: "Indonesia",
    },
    distance: 400,
    period: {
      days: 7,
      nights: 6,
    },
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [{name: "Alice Brown", rating: 5.0, comment: "Paradise!"}],
    photos: ["/tour-images/tour-img02.jpg", "/tour-images/tour-img02-2.jpg"],
    featured: true,
  },
  {
    title: "Snowy Mountains, Thailands",
    city: "Bangkok",
    address: {
      line1: "Somewhere in Thailand",
      line2: "",
      city: "Bangkok",
      state: "Bangkok",
      zip: "00000",
      country: "Thailand",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [],
    photos: ["/tour-images/tour-img03.jpg"],
    featured: true,
  },
  {
    title: "Beautiful Sunrise, Thailand",
    city: "Phuket",
    period: {
      days: 7,
      nights: 6,
    },
    address: {
      line1: "Somewhere in Thailand",
      line2: "",
      city: "Phuket",
      state: "Phuket",
      zip: "00000",
      country: "Thailand",
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [{name: "Traveler X", rating: 4.2}],
    photos: ["/tour-images/tour-img04.jpg", "/tour-images/tour-img04-2.jpg"],
    featured: true,
  },
  {
    title: "Nusa Pendia, Bali, Indonesia",
    city: "Bali",
    address: {
      line1: "Somewhere in Indonesia",
      line2: "",
      city: "Bali",
      state: "Bali",
      zip: "00000",
      country: "Indonesia",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [],
    photos: ["/tour-images/tour-img05.jpg"],
    featured: true,
  },
  {
    title: "Cherry Blossoms Spring",
    city: "Tokyo",
    address: {
      line1: "Somewhere in Japan",
      line2: "",
      city: "Tokyo",
      state: "Tokyo",
      zip: "00000",
      country: "Japan",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [{name: "Sato", rating: 4.8, comment: "Amazing blossoms."}],
    photos: ["/tour-images/tour-img06.jpg", "/tour-images/tour-img06-2.jpg"],
    featured: true,
  },
  {
    title: "Holmen Lofoten, France",
    city: "Paris",
    address: {
      line1: "Somewhere in France",
      line2: "",
      city: "Paris",
      state: "Paris",
      zip: "00000",
      country: "France",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [],
    photos: ["/tour-images/tour-img07.jpg"],
    featured: true,
  },
  {
    title: "Snowy Mountains, Thailand",
    city: "Bangkok",
    address: {
      line1: "Somewhere in Thailand",
      line2: "",
      city: "Bangkok",
      state: "Bangkok",
      zip: "00000",
      country: "Thailand",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [{name: "Visitor", rating: 3.9}],
    photos: ["/tour-images/tour-img03.jpg"],
    featured: true,
  },
  {
    title: "Jaflong, Sylhet",
    city: "Sylhet",
    address: {
      line1: "Somewhere in Sylhet",
      line2: "",
      city: "Sylhet",
      state: "Sylhet",
      zip: "00000",
      country: "Bangladesh",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 100,
    price: 99,
    maxGroupSize: 5,
    desc: "this is the description",
    reviews: [],
    photos: ["/tour-images/tour-img08.jpg"],
    featured: false,
  },
  {
    title: "Cox's Bazar Sea Beach",
    city: "Chittagong",
    address: {
      line1: "Somewhere in Chittagong",
      line2: "",
      city: "Chittagong",
      state: "Chittagong",
      zip: "00000",
      country: "Bangladesh",
    },
    period: {
      days: 7,
      nights: 6,
    },
    distance: 500,
    price: 99,
    maxGroupSize: 8,
    desc: "this is the description",
    reviews: [],
    photos: ["/tour-images/tour-img09.jpg"],
    featured: false,
  },
];

export default tours;
